### ISSUE TITLE
Next button doesn't work

### ISSUE THREAD

**Issue by nicomontanari98** [ascoders/react-native-image-viewer#206]
![screenshot](https://user-images.githubusercontent.com/15747776/41960833-0d1642f4-79f1-11e8-9fab-e0acc84f6d05.png)

**Comment by nicomontanari98** [comment]
These are the buttons.
They are rendered but when i click the right button it doesn't work.
You declared 2 functions (goBack and goNext) in two different ways and the problem could be the context.

`renderArrowLeft={() => this.state.modalIndex !== 0 ? <View style={{
     backgroundColor: 'rgba(0, 0, 0, 0.3)',
     padding: 5,
     borderRadius: 15,
     marginLeft: 5
 }}>
      <MaterialIcon name="keyboard-arrow-left" size={25} color={PRIMARY_COLOR}/>
 </View> : null}`
`renderArrowRight={() => this.state.modalIndex !== this.state.images.length - 1 ? <View style={{
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      padding: 5,
      borderRadius: 15,
      marginRight: 5
}}>
     <MaterialIcon name="keyboard-arrow-right" size={25} color={PRIMARY_COLOR}/>
</View> : null
`

**Comment by ascoders** [comment]
Thanks for your reply, this problem has been fixed in new version `2.2.11`.

**Comment by jsh854** [comment]
This still doesnt work in 3.0.1 , any permanent fix you guys came up with for this?
