### ISSUE TITLE
Warning useNativeDriver and componentWillReceiveProps how to solve?

### ISSUE THREAD

**Issue by Larva02** [ascoders/react-native-image-viewer#398]
![image](https://user-images.githubusercontent.com/12692666/81934140-08908e80-9621-11ea-9f95-2dc6bee53935.png)

Today (May 14th) I used this component for the first time，What went wrong？

**Comment by LuongTruong** [comment]
This has been mentioned quite a lot of time. Did you make any process, @ascoders ? I face the same issue

**Comment by GoktuqCan** [comment]
`v3.0.0` has commit by @petertravelchime about `useNativeDriver` but warning still showing.

**Comment by ArtemKolichenkov** [comment]
Hey guys, I'm a new maintainer for this repo and I'm trying to resolve most common issues right now. Read more in #396. It still might take time to make into release, but at least I can say that next release is soon (like a week or so). I will notify people here to update once the new version is out.

@GoktuqCan yeah, technically it is in the repo already, but it was not released to npm. So next version will have it.

**Comment by Larva02** [comment]
I have updated to 3.0.1 and found that this problem has been solved，thanks @ArtemKolichenkov

**Comment by dl-husky73** [comment]
I having upgraded to 3.0.1 and I am getting the Animated: useNativeDriver was not specified.  I am trying to catch up on these notes, but wondering did anyone get rid of the useNativeDriver warning?

**Comment by bluenex** [comment]
> I having upgraded to 3.0.1 and I am getting the Animated: useNativeDriver was not specified. I am trying to catch up on these notes, but wondering did anyone get rid of the useNativeDriver warning?

I just upgraded the lib to 3.0.1 today and still get the warning

```
Warning
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
```

```js
function shouldUseNativeDriver(
  config: {...AnimationConfig, ...} | EventConfig,
): boolean {
  if (config.useNativeDriver == null) {
    console.warn(
      'Animated: `useNativeDriver` was not specified. This is a required ' +
        'option and must be explicitly set to `true` or `false`',
    );
  }
...
```

**Comment by pxpeterxu** [comment]
If you're still getting the warning, check that it's coming from this library! It's possible that some other library is causing it.

Also, if you're using `yarn.lock` or have a `package-lock.json`, take a look at that file and see the version of `react-native-image-pan-zoom`. Make sure you're using version 2.1.12. Likewise, if `react-native-image-pan-zoom` is in your `package.json`, make sure it's marked as `"react-native-image-pan-zoom": "^2.1.12"`
